'Isolated agents' : {
        'Dist 1 Level 2' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T0/',
        'Dist 1 Level 3' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T1/',
        'Dist 1 Level 4' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T2/',
        'Dist 1 Level 5' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T3/',
        'Dist 1 Level 6' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T4/',
        'Dist 1 Level 7' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T5/',
        'Dist 1 Level 8' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T6/',

        'Dist 2 Level 2' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T10/',
        'Dist 2 Level 3' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T11/',
        'Dist 2 Level 4' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T12/',
        'Dist 2 Level 5' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T13/',
        'Dist 2 Level 6' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T14/',
        'Dist 2 Level 7' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T15/',
        'Dist 2 Level 8' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T16/',
        
        'Dist 3 Level 2' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T20/',
        'Dist 3 Level 3' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T21/',
        'Dist 3 Level 4' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T22/',
        'Dist 3 Level 5' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T23/',
        'Dist 3 Level 6' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T24/',
        'Dist 3 Level 7' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T25/',
        'Dist 3 Level 8' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T26/',

        'Dist 4 Level 2' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T30/',
        'Dist 4 Level 3' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T31/',
        'Dist 4 Level 4' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T32/',
        'Dist 4 Level 5' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T33/',
        'Dist 4 Level 6' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T34/',
        'Dist 4 Level 7' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T35/',
        'Dist 4 Level 8' : 'AAAI_EXPERIMENTS/ablations/four_dist/no_comm/T36/',
    },